name: Lint and Check

on:
  pull_request:
    branches: [main]

jobs:
  lint-and-check:
    name: Run Biome Lint and Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup dependencies
        id: setup
        uses: ./.github/actions/setup-deps

      - name: Run Biome Lint & Formatter
        run: ${{ steps.setup.outputs.runner }} lint src/ tina/
